language: python
matrix:
  include:
   - os: linux
     dist: trusty
     sudo: false
     python: '3.6'
# If your build needs more advanced behavior, see detailed Travis CI instructions:
# https://docs.travis-ci.com/user/languages/python/
script: ./setup.sh

after_success:
  - bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)
